version: '3'

services:

  blockstore:
    container_name: edx.devstack.blockstore
    image: opencraft/blockstore:latest
    build:
      context: .
      dockerfile: Dockerfile-dev
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]
    networks:
      - default
      - devstack
    ports:
      - "18250:18250"
    volumes:
      - ./:/blockstore/app/:cached

networks:
  devstack:
    external:
      name: devstack_default
